# Dockerfile.dev

FROM golang:1.24-alpine

WORKDIR /app

# Install git and ca-certificates for Go modules
RUN apk add --no-cache git ca-certificates && update-ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /evento cmd/evento/main.go

EXPOSE 8080

CMD ["/evento"]
